var tableData=[],editorTable=null,chartsConfig=window.typeConfig,resizeTimer=null,currentChartType=0;
window.onload=function(){(editorTable=domUtils.findParentByTagName(editor.selection.getRange().startContainer,"table",!0))?(initChartsTypeView(),renderTable(editorTable),initEvent(),initUserConfig(editorTable.getAttribute("data-chart")),$("#scrollBed .view-box:eq("+currentChartType+")").trigger("click"),updateViewType(currentChartType),dialog.addListener("resize",function(){null!=resizeTimer&&window.clearTimeout(resizeTimer);resizeTimer=window.setTimeout(function(){resizeTimer=null;renderCharts()},
500)})):document.body.innerHTML="<div class='edui-charts-not-data'>\u672a\u627e\u5230\u6570\u636e</div>"};function initChartsTypeView(){for(var a=[],b=0,c=chartsConfig.length;b<c;b++)a.push('<div class="view-box" data-chart-type="'+b+'"><img width="300" src="images/charts'+b+'.png"></div>');$("#scrollBed").html(a.join(""))}
function renderTable(a){for(var b=[],c=0,d;d=a.rows[c];c++){tableData[c]=[];b[c]=[];for(var f=0,e;e=d.cells[f];f++)e=getCellValue(e),0<c&&0<f&&(e=+e),0===c||0===f?b[c].push("<th>"+e+"</th>"):b[c].push('<td><input type="text" class="data-item" value="'+e+'"></td>'),tableData[c][f]=e;b[c]=b[c].join("")}$("#tableContainer").html('<table id="showTable" border="1"><tbody><tr>'+b.join("</tr><tr>")+"</tr></tbody></table>")}
function initUserConfig(a){var b={};a&&(a=a.split(";"),$.each(a,function(a,d){d=d.split(":");b[d[0]]=d[1]}),setUserConfig(b))}
function initEvent(){var a=null,b=chartsConfig.length-1,c=$("#scrollBed .view-box");$(".charts-format").delegate(".format-ctrl","change",function(){renderCharts()});$(".table-view").delegate(".data-item","focus",function(){a=this.value}).delegate(".data-item","blur",function(){this.value!==a&&renderCharts();a=null});$("#buttonContainer").delegate("a","click",function(a){a.preventDefault();"prev"===this.getAttribute("data-title")?0<currentChartType&&(currentChartType--,updateViewType(currentChartType)):
currentChartType<b&&(currentChartType++,updateViewType(currentChartType))});$("#scrollBed").delegate(".view-box","click",function(a){a=$(this).attr("data-chart-type");c.removeClass("selected");$(c[a]).addClass("selected");currentChartType=a|0;currentChartType===chartsConfig.length-1?disableNotPieConfig():enableNotPieConfig();renderCharts()})}
function renderCharts(){var a=collectData();$("#chartsContainer").highcharts($.extend({},chartsConfig[currentChartType],{credits:{enabled:!1},exporting:{enabled:!1},title:{text:a.title,x:-20},subtitle:{text:a.subTitle,x:-20},xAxis:{title:{text:a.xTitle},categories:a.categories},yAxis:{title:{text:a.yTitle},plotLines:[{value:0,width:1,color:"#808080"}]},tooltip:{enabled:!0,valueSuffix:a.suffix},legend:{layout:"vertical",align:"right",verticalAlign:"middle",borderWidth:1},series:a.series}))}
function updateViewType(a){$("#scrollBed").css("marginLeft",324*-a+"px")}function collectData(){var a=document.forms["data-form"],b=null;currentChartType!==chartsConfig.length-1?(b=getSeriesAndCategories(),$.extend(b,getUserConfig())):(b=getSeriesForPieChart(),b.title=a.title.value,b.suffix=a.unit.value);return b}
function getUserConfig(){var a=document.forms["data-form"];return{title:a.title.value,subTitle:a["sub-title"].value,xTitle:a["x-title"].value,yTitle:a["y-title"].value,suffix:a.unit.value,tableDataFormat:getTableDataFormat(),tip:$("#tipInput").val()}}
function setUserConfig(a){var b=document.forms["data-form"];a.title&&(b.title.value=a.title);a.subTitle&&(b["sub-title"].value=a.subTitle);a.xTitle&&(b["x-title"].value=a.xTitle);a.yTitle&&(b["y-title"].value=a.yTitle);a.suffix&&(b.unit.value=a.suffix);"-1"==a.dataFormat&&(b["charts-format"][1].checked=!0);a.tip&&(b.tip.value=a.tip);currentChartType=a.chartType||0}
function getSeriesAndCategories(){var a=[],b=[],b=[],c=getTableData();if("-1"===getTableDataFormat()){for(var d=0,f=c.length;d<f;d++)for(var e=0,g=c[d].length;e<g;e++)b[e]||(b[e]=[]),b[e][d]=c[d][e];c=b}b=c[0].slice(1);for(d=1;f=c[d];d++)a.push({name:f[0],data:f.slice(1)});return{series:a,categories:b}}function getTableDataFormat(){var a=document.forms["data-form"]["charts-format"];return a[0].checked?a[0].value:a[1].value}function disableNotPieConfig(){updateConfigItem("disable")}
function enableNotPieConfig(){updateConfigItem("enable")}function updateConfigItem(a){var b=$("#showTable")[0];a="disable"===a?!0:!1;for(var c=2,d;d=b.rows[c];c++)for(var f=1,e;e=d.cells[f];f++)$("input",e).attr("disabled",a);$("input.not-pie-item").attr("disabled",a);$("#tipInput").attr("disabled",!a)}function getSeriesForPieChart(){for(var a={type:"pie",name:$("#tipInput").val(),data:[]},b=getTableData(),c=1,d=b[0].length;c<d;c++)a.data.push([b[0][c],b[1][c]]);return{series:[a]}}
function getTableData(){for(var a=document.getElementById("showTable").rows[0].cells.length-1,b=getTableInputValue(),c=0;b[c];c++)tableData[Math.floor(c/a)+1][c%a+1]=b[c];return tableData}function getTableInputValue(){for(var a=document.getElementById("showTable").getElementsByTagName("input"),b=[],c=0,d;d=a[c];c++)b.push(d.value|0);return b}function getCellValue(a){return utils.trim(a.innerText||a.textContent||"").replace(new RegExp(UE.dom.domUtils.fillChar,"g"),"").replace(/^\s+|\s+$/g,"")}
dialog.onok=function(){var a=getUserConfig();a.chartType=currentChartType;syncTableData();editor.execCommand("charts",a)};function syncTableData(){for(var a=getTableData(),b=1,c;c=editorTable.rows[b];b++)for(var d=1,f;f=c.cells[d];d++)f.innerHTML=a[b][d]};