function Music(){this.init()}
(function(){var k=[],l=[],e=null;Music.prototype={total:70,pageSize:10,dataUrl:"http://tingapi.ting.baidu.com/v1/restserver/ting?method=baidu.ting.search.common",playerUrl:"http://box.baidu.com/widget/flash/bdspacesong.swf",init:function(){var a=this;domUtils.on($G("J_searchName"),"keyup",function(b){13==(window.event||b).keyCode&&a.dosearch()});domUtils.on($G("J_searchBtn"),"click",function(){a.dosearch()})},callback:function(a){var b=this;b.data=a.song_list;setTimeout(function(){$G("J_resultBar").innerHTML=b._renderTemplate(a.song_list)},
300)},dosearch:function(){e=null;var a=$G("J_searchName").value;if(""==utils.trim(a))return!1;a=encodeURIComponent(a);this._sent(a)},doselect:function(a){"object"==typeof a?e=a:"number"==typeof a&&(e=this.data[a])},onpageclick:function(a){for(var b=0;b<k.length;b++)$G(k[b]).className="pageoff",$G(l[b]).className="paneloff";$G("page"+a).className="pageon";$G("panel"+a).className="panelon"},listenTest:function(a){var b=$G("J_preview"),f="m-try"==a.className,d=this._getTryingElem();d&&(d.className="m-try",
b.innerHTML="");f&&(a.className="m-trying",b.innerHTML=this._buildMusicHtml(this._getUrl(!0)))},_sent:function(a){$G("J_resultBar").innerHTML='<div class="loading"></div>';utils.loadFile(document,{src:this.dataUrl+"&query="+a+"&page_size="+this.total+"&callback=music.callback&.r="+Math.random(),tag:"script",type:"text/javascript",defer:"defer"})},_removeHtml:function(a){return a.replace(/<\s*\/?\s*[^>]*\s*>/gi,"")},_getUrl:function(a){a="from=tiebasongwidget&url=&name="+encodeURIComponent(this._removeHtml(e.title))+
"&artist="+encodeURIComponent(this._removeHtml(e.author))+"&extra="+encodeURIComponent(this._removeHtml(e.album_title))+"&autoPlay="+a+"&loop=true";return this.playerUrl+"?"+a},_getTryingElem:function(){for(var a=$G("J_listPanel").getElementsByTagName("span"),b=0;b<a.length;b++)if("m-trying"==a[b].className)return a[b];return null},_buildMusicHtml:function(a){a='<embed class="BDE_try_Music" allowfullscreen="false" pluginspage="http://www.macromedia.com/go/getflashplayer"'+(' src="'+a+'"')+' width="1" height="1" style="position:absolute;left:-2000px;"';
a+=' type="application/x-shockwave-flash" wmode="transparent" play="true" loop="false"';return a+=' menu="false" allowscriptaccess="never" scale="noborder">'},_byteLength:function(a){return a.replace(/[^\u0000-\u007f]/g,"aa").length},_getMaxText:function(a){a=this._removeHtml(a);if(12<this._byteLength(a))return a.substring(0,5)+"...";a||(a="&nbsp;");return a},_rebuildData:function(a){for(var b=[],f=this.pageSize,d,c=0;c<a.length;c++)0==(c+f)%f&&(d=[],b.push(d)),d.push(a[c]);return b},_renderTemplate:function(a){if(0==
a.length)return'<div class="empty">'+lang.emptyTxt+"</div>";a=this._rebuildData(a);var b=[],f=[],d=[];b.push('<div id="J_listPanel" class="listPanel">');f.push('<div class="page">');for(var c=0,e;e=a[c++];){l.push("panel"+c);k.push("page"+c);1==c?(b.push('<div id="panel'+c+'" class="panelon">'),1!=a.length&&d.push('<div id="page'+c+'" onclick="music.onpageclick('+c+')" class="pageon">'+c+"</div>")):(b.push('<div id="panel'+c+'" class="paneloff">'),d.push('<div id="page'+c+'" onclick="music.onpageclick('+
c+')" class="pageoff">'+c+"</div>"));b.push('<div class="m-box">');b.push('<div class="m-h"><span class="m-t">'+lang.chapter+'</span><span class="m-s">'+lang.singer+'</span><span class="m-z">'+lang.special+'</span><span class="m-try-t">'+lang.listenTest+"</span></div>");for(var g=0,h;h=e[g++];)b.push('<label for="radio-'+c+"-"+g+'" class="m-m">'),b.push('<input type="radio" id="radio-'+c+"-"+g+'" name="musicId" class="m-l" onclick="music.doselect('+(this.pageSize*(c-1)+(g-1))+')"/>'),b.push('<span class="m-t">'+
this._getMaxText(h.title)+"</span>"),b.push('<span class="m-s">'+this._getMaxText(h.author)+"</span>"),b.push('<span class="m-z">'+this._getMaxText(h.album_title)+"</span>"),b.push('<span class="m-try" onclick="music.doselect('+(this.pageSize*(c-1)+(g-1))+');music.listenTest(this)"></span>'),b.push("</label>");b.push("</div>");b.push("</div>")}d.reverse();f.push(d.join(""));b.push("</div>");f.push("</div>");return b.join("")+f.join("")},exec:function(){null!=e&&($G("J_preview").innerHTML="",editor.execCommand("music",
{url:this._getUrl(!1),width:400,height:95}))}}})();