(function(){function E(){for(var a=$G("tabHeads").children,b=0;b<a.length;b++)domUtils.on(a[b],"click",function(b){var k,c=b.target||b.srcElement;for(b=0;b<a.length;b++)k=a[b].getAttribute("data-content-id"),a[b]==c?(domUtils.addClass(a[b],"focus"),domUtils.addClass($G(k),"focus")):(domUtils.removeClasses(a[b],"focus"),domUtils.removeClasses($G(k),"focus"))})}function F(){dialog.onok=function(){$G("preview").innerHTML="";switch(v("tabHeads","tabSrc")){case "video":var a;a=$G("videoWidth");var b=$G("videoHeight"),
d=$G("videoUrl").value,k=v("videoFloat","name");if(d){var c;b:{c=[a,b];for(var e=0,g;g=c[e++];){var n=g.value;if(!/(0|^[1-9]\d*$)/.test(n)&&n){alert(lang.numError);g.value="";g.focus();c=!1;break b}}c=!0}c?(editor.execCommand("insertvideo",{url:y(d),width:a.value,height:b.value,align:k},z?"upload":null),a=void 0):a=!1}else a=!1;return a;case "videoSearch":a=domUtils.getElementsByTagName($G("searchList"),"img");b=[];for(d=0;k=a[d++];)k.getAttribute("selected")&&b.push({url:k.getAttribute("ue_video_url"),
width:420,height:280,align:"none"});editor.execCommand("insertvideo",b);break;case "upload":a=[];b=editor.getOpt("videoUrlPrefix");d=$G("upload_width").value||420;k=$G("upload_height").value||280;c=v("upload_alignment","name")||"none";for(e in C)a.push({url:b+C[e].url,width:d,height:k,align:c});(b=A.getQueueCount())?($(".info","#queueList").html('<span style="color:red;">'+"\u8fd8\u67092\u4e2a\u672a\u4e0a\u4f20\u6587\u4ef6".replace(/[\d]/,b)+"</span>"),a=!1):(editor.execCommand("insertvideo",a,"upload"),
a=void 0);return a}};dialog.oncancel=function(){$G("preview").innerHTML=""}}function v(a,b){for(var d=$G(a).children,k,c=0,e;e=d[c++];)if("focus"==e.className){k=e.getAttribute(b);break}return k}function y(a){return a?a=utils.trim(a).replace(/v\.youku\.com\/v_show\/id_([\w\-=]+)\.html/i,"player.youku.com/player.php/sid/$1/v.swf").replace(/(www\.)?youtube\.com\/watch\?v=([\w\-]+)/i,"www.youtube.com/v/$2").replace(/youtu.be\/(\w+)$/i,"www.youtube.com/v/$1").replace(/v\.ku6\.com\/.+\/([\w\.]+)\.html.*$/i,
"player.ku6.com/refer/$1/v.swf").replace(/www\.56\.com\/u\d+\/v_([\w\-]+)\.html/i,"player.56.com/v_$1.swf").replace(/www.56.com\/w\d+\/play_album\-aid\-\d+_vid\-([^.]+)\.html/i,"player.56.com/v_$1.swf").replace(/v\.pps\.tv\/play_([\w]+)\.html.*$/i,"player.pps.tv/player/sid/$1/v.swf").replace(/www\.letv\.com\/ptv\/vplay\/([\d]+)\.html.*$/i,"i7.imgs.letv.com/player/swfPlayer.swf?id=$1&autoplay=0").replace(/www\.tudou\.com\/programs\/view\/([\w\-]+)\/?/i,"www.tudou.com/v/$1").replace(/v\.qq\.com\/cover\/[\w]+\/[\w]+\/([\w]+)\.html/i,
"static.video.qq.com/TPout.swf?vid=$1").replace(/v\.qq\.com\/.+[\?\&]vid=([^&]+).*$/i,"static.video.qq.com/TPout.swf?vid=$1").replace(/my\.tv\.sohu\.com\/[\w]+\/[\d]+\/([\d]+)\.shtml.*$/i,"share.vrs.sohu.com/my/v.swf&id=$1"):""}function G(a){var b=$G(a).children;a=0;for(var d;d=b[a++];)domUtils.on(d,"click",function(){for(var a=0,d;d=b[a++];)d.className="",d.removeAttribute&&d.removeAttribute("class");this.className="focus"})}function H(a){browser.ie?a.onpropertychange=function(){p(this.value)}:a.addEventListener("input",
function(){p(this.value)},!1)}function p(a){a&&(a=y(a),$G("preview").innerHTML='<div class="previewMsg"><span>'+lang.urlError+'</span></div><embed class="previewVideo" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" src="'+a+'" width="420" height="280" wmode="transparent" play="true" loop="false" menu="false" allowscriptaccess="never" allowfullscreen="true" ></embed>')}function B(a){this.$wrap=a.constructor==String?$("#"+a):$(a);this.init()}var C=[],
z=!1,A;window.onload=function(){$focus($G("videoUrl"));E();for(var a=["videoFloat","upload_alignment"],b=0,d;d=a[b++];){var k=$G(d),c={none:lang["default"],left:lang.floatLeft,right:lang.floatRight,center:lang.block},e;for(e in c){var g=document.createElement("div");g.setAttribute("name",e);"none"==e&&(g.className="focus");g.style.cssText="background:url(images/"+e+"_focus.jpg);";g.setAttribute("title",c[e]);k.appendChild(g)}G(d)}H($G("videoUrl"));F();var b=editor.selection.getRange().getClosedNode(),
n;if(b&&b.className){d="edui-faked-video"==b.className;a=-1!=b.className.indexOf("edui-upload-video");if(d||a)for($G("videoUrl").value=n=b.getAttribute("_url"),$G("videoWidth").value=b.width,$G("videoHeight").value=b.height,d=domUtils.getComputedStyle(b,"float"),b="center"===domUtils.getComputedStyle(b.parentNode,"text-align")?"center":d,d=$G("videoFloat").children,k=0;c=d[k++];)c.getAttribute("name")==b?"focus"!=c.className&&(c.className="focus"):"focus"==c.className&&(c.className="");a&&(z=!0)}p(n);
A=new B("queueList")};B.prototype={init:function(){this.fileList=[];this.initContainer();this.initUploader()},initContainer:function(){this.$queue=this.$wrap.find(".filelist")},initUploader:function(){function a(f){var a=e('<li id="'+f.id+'"><p class="title">'+f.name+'</p><p class="imgWrap"></p><p class="progress"><span></span></p></li>'),b=e('<div class="file-panel"><span class="cancel">'+lang.uploadDelete+'</span><span class="rotateRight">'+lang.uploadTurnRight+'</span><span class="rotateLeft">'+
lang.uploadTurnLeft+"</span></div>").appendTo(a),d=a.find("p.progress span"),c=a.find("p.imgWrap"),k=e('<p class="error"></p>').hide().appendTo(a),g=function(a){switch(a){case "exceed_size":text=lang.errorExceedSize;break;case "interrupt":text=lang.errorInterrupt;break;case "http":text=lang.errorHttp;break;case "not_allow_type":text=lang.errorFileType;break;default:text=lang.errorUploadRetry}k.text(text).show()};"invalid"===f.getStatus()?g(f.statusText):(c.text(lang.uploadPreview),-1=="|png|jpg|jpeg|bmp|gif|".indexOf("|"+
f.ext.toLowerCase()+"|")?c.empty().addClass("notimage").append('<i class="file-preview file-type-'+f.ext.toLowerCase()+'"></i><span class="file-title">'+f.name+"</span>"):browser.ie&&7>=browser.version?c.text(lang.uploadNoPreview):h.makeThumb(f,function(a,f){if(a||!f||/^data:/.test(f)&&browser.ie&&7>=browser.version)c.text(lang.uploadNoPreview);else{var b=e('<img src="'+f+'">');c.empty().append(b);b.on("error",function(){c.text(lang.uploadNoPreview)})}},y,z),t[f.id]=[f.size,0],f.rotation=0,f.ext&&
-1!=B.indexOf(f.ext.toLowerCase())||(g("not_allow_type"),h.removeFile(f)));f.on("statuschange",function(c,e){"progress"===e?d.hide().width(0):"queued"===e&&(a.off("mouseenter mouseleave"),b.remove());"error"===c||"invalid"===c?(g(f.statusText),t[f.id][1]=1):"interrupt"===c?g("interrupt"):"queued"===c?t[f.id][1]=0:"progress"===c&&(k.hide(),d.css("display","block"));a.removeClass("state-"+e).addClass("state-"+c)});a.on("mouseenter",function(){b.stop().animate({height:30})});a.on("mouseleave",function(){b.stop().animate({height:0})});
b.on("click","span",function(){var a;switch(e(this).index()){case 0:h.removeFile(f);return;case 1:f.rotation+=90;break;case 2:f.rotation-=90}A?(a="rotate("+f.rotation+"deg)",c.css({"-webkit-transform":a,"-mos-transform":a,"-o-transform":a,transform:a})):c.css("filter","progid:DXImageTransform.Microsoft.BasicImage(rotation="+~~(f.rotation/90%4+4)%4+")")});a.insertBefore(v)}function b(){var a=0,b=0,c=q.children(),d;e.each(t,function(d,c){b+=c[0];a+=c[0]*c[1]});d=b?a/b:0;c.eq(0).text(Math.round(100*
d)+"%");c.eq(1).css("width",Math.round(100*d)+"%");k()}function d(a,b){if(a!=l){var e=h.getStats();m.removeClass("state-"+l);m.addClass("state-"+a);switch(a){case "pedding":n.addClass("element-invisible");w.addClass("element-invisible");p.removeClass("element-invisible");q.hide();r.hide();h.refresh();break;case "ready":p.addClass("element-invisible");n.removeClass("element-invisible");w.removeClass("element-invisible");q.hide();r.show();m.text(lang.uploadStart);h.refresh();break;case "uploading":q.show();
r.hide();m.text(lang.uploadPause);break;case "paused":q.show();r.hide();m.text(lang.uploadContinue);break;case "confirm":q.show();r.hide();m.text(lang.uploadStart);e=h.getStats();if(e.successNum&&!e.uploadFailNum){d("finish");return}break;case "finish":q.hide(),r.show(),e.uploadFailNum?m.text(lang.uploadRetry):m.text(lang.uploadStart)}l=a;k()}c.getQueueCount()?m.removeClass("disabled"):m.addClass("disabled")}function k(){var a="",b;"ready"===l?a=lang.updateStatusReady.replace("_",x).replace("_KB",
WebUploader.formatSize(u)):"confirm"===l?(b=h.getStats(),b.uploadFailNum&&(a=lang.updateStatusConfirm.replace("_",b.successNum).replace("_",b.successNum))):(b=h.getStats(),a=lang.updateStatusFinish.replace("_",x).replace("_KB",WebUploader.formatSize(u)).replace("_",b.successNum),b.uploadFailNum&&(a+=lang.updateStatusError.replace("_",b.uploadFailNum)));r.html(a)}var c=this,e=jQuery,g=c.$wrap,n=g.find(".filelist"),w=g.find(".statusBar"),r=w.find(".info"),m=g.find(".uploadBtn");g.find(".filePickerBtn");
var v=g.find(".filePickerBlock"),p=g.find(".placeholder"),q=w.find(".progress").hide(),x=0,u=0,g=window.devicePixelRatio||1,y=113*g,z=113*g,l="",t={},A=function(){var a=document.createElement("p").style;return"transition"in a||"WebkitTransition"in a||"MozTransition"in a||"msTransition"in a||"OTransition"in a}(),h,D=editor.getActionUrl(editor.getOpt("videoActionName")),g=editor.getOpt("videoMaxSize"),B=(editor.getOpt("videoAllowFiles")||[]).join("").replace(/\./g,",").replace(/^[,]/,"");WebUploader.Uploader.support()?
editor.getOpt("videoActionName")?(h=c.uploader=WebUploader.create({pick:{id:"#filePickerReady",label:lang.uploadSelectFile},swf:"../../third-party/webuploader/Uploader.swf",server:D,fileVal:editor.getOpt("videoFieldName"),duplicate:!0,fileSingleSizeLimit:g,compress:!1}),h.addButton({id:"#filePickerBlock"}),h.addButton({id:"#filePickerBtn",label:lang.uploadAddFile}),d("pedding"),h.on("fileQueued",function(b){x++;u+=b.size;1===x&&(p.addClass("element-invisible"),w.show());a(b)}),h.on("fileDequeued",
function(a){x--;u-=a.size;var c=e("#"+a.id);delete t[a.id];b();c.off().find(".file-panel").off().end().remove();b()}),h.on("filesQueued",function(a){h.isInProgress()||"pedding"!=l&&"finish"!=l&&"confirm"!=l&&"ready"!=l||d("ready");b()}),h.on("all",function(a,b){switch(a){case "uploadFinished":d("confirm",b);break;case "startUpload":var c=utils.serializeParam(editor.queryCommandValue("serverparam"))||"",c=utils.formatUrl(D+(-1==D.indexOf("?")?"?":"&")+"encode=utf-8&"+c);h.option("server",c);d("uploading",
b);break;case "stopUpload":d("paused",b)}}),h.on("uploadBeforeSend",function(a,b,c){c.X_Requested_With="XMLHttpRequest"}),h.on("uploadProgress",function(a,c){e("#"+a.id).find(".progress span").css("width",100*c+"%");t[a.id][1]=c;b()}),h.on("uploadSuccess",function(a,b){var c=e("#"+a.id);try{var d=utils.str2json(b._raw||b);"SUCCESS"==d.state?(C.push({url:d.url,type:d.type,original:d.original}),c.append('<span class="success"></span>')):c.find(".error").text(d.state).show()}catch(g){c.find(".error").text(lang.errorServerUpload).show()}}),
h.on("uploadError",function(a,b){}),h.on("error",function(b,c){"Q_TYPE_DENIED"!=b&&"F_EXCEED_SIZE"!=b||a(c)}),h.on("uploadComplete",function(a,b){}),m.on("click",function(){if(e(this).hasClass("disabled"))return!1;"ready"===l?h.upload():"paused"===l?h.upload():"uploading"===l&&h.stop()}),m.addClass("state-"+l),b()):e("#filePickerReady").after(e("<div>").html(lang.errorLoadConfig)).hide():e("#filePickerReady").after(e("<div>").html(lang.errorNotSupport)).hide()},getQueueCount:function(){var a,b,d=
0,k=this.uploader.getFiles();for(b=0;a=k[b++];)a=a.getStatus(),"queued"!=a&&"uploading"!=a&&"progress"!=a||d++;return d},refresh:function(){this.uploader.refresh()}}})();