(function(b){"function"===typeof define&&define.amd?define(["jquery"],b):b(jQuery)})(function(b){var h=b.fn.placard,f=function(a,d){var c=this;this.$element=b(a);this.options=b.extend({},b.fn.placard.defaults,d);this.$accept=this.$element.find(".placard-accept");this.$cancel=this.$element.find(".placard-cancel");this.$field=this.$element.find(".placard-field");this.$footer=this.$element.find(".placard-footer");this.$header=this.$element.find(".placard-header");this.$popup=this.$element.find(".placard-popup");
this.actualValue=null;this.clickStamp="_";this.previousValue="";-1===this.options.revertOnCancel&&(this.options.revertOnCancel=0<this.$accept.length?!0:!1);this.isInput=this.$field.is("input");this.$field.on("focus.fu.placard",b.proxy(this.show,this));this.$field.on("keydown.fu.placard",b.proxy(this.keyComplete,this));this.$accept.on("click.fu.placard",b.proxy(this.complete,this,"accept"));this.$cancel.on("click.fu.placard",function(a){a.preventDefault();c.complete("cancel")});this.ellipsis()};f.prototype=
{constructor:f,complete:function(a){var b=this.options["on"+a[0].toUpperCase()+a.substring(1)],c={previousValue:this.previousValue,value:this.$field.val()};b?(b(c),this.$element.trigger(a,c)):("cancel"===a&&this.options.revertOnCancel&&this.$field.val(this.previousValue),this.$element.trigger(a,c),this.hide())},keyComplete:function(a){this.isInput&&13===a.keyCode?(this.complete("accept"),this.$field.blur()):27===a.keyCode&&(this.complete("cancel"),this.$field.blur())},destroy:function(){this.$element.remove();
b(document).off("click.fu.placard.externalClick."+this.clickStamp);this.$element.find("input").each(function(){b(this).attr("value",b(this).val())});return this.$element[0].outerHTML},disable:function(){this.$element.addClass("disabled");this.$field.attr("disabled","disabled");this.hide()},ellipsis:function(){var a,b,c;if("true"===this.$element.attr("data-ellipsis"))if(a=this.$field.get(0),this.$field.is("input"))a.scrollLeft=0;else if(a.scrollTop=0,a.clientHeight<a.scrollHeight){this.actualValue=
this.$field.val();this.$field.val("");c="";for(b=0;a.clientHeight>=a.scrollHeight;)c+=this.actualValue[b],this.$field.val(c+"..."),b++;c=0<c.length?c.substring(0,c.length-1):"";this.$field.val(c+"...")}},enable:function(){this.$element.removeClass("disabled");this.$field.removeAttr("disabled")},externalClickListener:function(a,b){(!0===b||this.isExternalClick(a))&&this.complete(this.options.externalClickAction)},getValue:function(){return null!==this.actualValue?this.actualValue:this.$field.val()},
hide:function(){this.$element.hasClass("showing")&&(this.$element.removeClass("showing"),this.ellipsis(),b(document).off("click.fu.placard.externalClick."+this.clickStamp),this.$element.trigger("hidden.fu.placard"))},isExternalClick:function(a){var d=this.$element.get(0),c=this.options.externalClickExceptions||[],e=b(a.target);if(a.target===d||e.parents(".placard:first").get(0)===d)return!1;a=0;for(d=c.length;a<d;a++)if(e.is(c[a])||0<e.parents(c[a]).length)return!1;return!0},setValue:function(a){this.$field.val(a);
this.$element.hasClass("showing")||this.ellipsis()},show:function(){var a;if(!this.$element.hasClass("showing")){a=b(document).find(".placard.showing");if(0<a.length){if(a.data("fu.placard")&&a.data("fu.placard").options.explicit)return;a.placard("externalClickListener",{},!0)}this.previousValue=this.$field.val();this.$element.addClass("showing");null!==this.actualValue&&(this.$field.val(this.actualValue),this.actualValue=null);0<this.$header.length&&this.$popup.css("top","-"+this.$header.outerHeight(!0)+
"px");0<this.$footer.length&&this.$popup.css("bottom","-"+this.$footer.outerHeight(!0)+"px");this.$element.trigger("shown.fu.placard");this.clickStamp=(new Date).getTime()+(Math.floor(100*Math.random())+1);if(!this.options.explicit)b(document).on("click.fu.placard.externalClick."+this.clickStamp,b.proxy(this.externalClickListener,this))}}};b.fn.placard=function(a){var d=Array.prototype.slice.call(arguments,1),c,e=this.each(function(){var e=b(this),g=e.data("fu.placard"),h="object"===typeof a&&a;g||
e.data("fu.placard",g=new f(this,h));"string"===typeof a&&(c=g[a].apply(g,d))});return void 0===c?e:c};b.fn.placard.defaults={onAccept:void 0,onCancel:void 0,externalClickAction:"cancel",externalClickExceptions:[],explicit:!1,revertOnCancel:-1};b.fn.placard.Constructor=f;b.fn.placard.noConflict=function(){b.fn.placard=h;return this};b(document).on("focus.fu.placard.data-api","[data-initialize=placard]",function(a){a=b(a.target).closest(".placard");a.data("fu.placard")||a.placard(a.data())});b(function(){b("[data-initialize=placard]").each(function(){var a=
b(this);a.data("fu.placard")||a.placard(a.data())})})});