var T,baidu=T=baidu||{version:"1.5.0"};baidu.guid="$BAIDU$";baidu.$$=window[baidu.guid]=window[baidu.guid]||{global:{}};baidu.flash=baidu.flash||{};baidu.dom=baidu.dom||{};baidu.dom.g=function(a){return a?"string"==typeof a||a instanceof String?document.getElementById(a):!a.nodeName||1!=a.nodeType&&9!=a.nodeType?null:a:null};baidu.g=baidu.G=baidu.dom.g;baidu.array=baidu.array||{};
baidu.each=baidu.array.forEach=baidu.array.each=function(a,b,d){var c,g,e=a.length;if("function"==typeof b)for(g=0;g<e&&(c=a[g],c=b.call(d||a,c,g),!1!==c);g++);return a};baidu.lang=baidu.lang||{};baidu.lang.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};baidu.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};baidu.isString=baidu.lang.isString;baidu.browser=baidu.browser||{};
baidu.browser.opera=/opera(\/| )(\d+(\.\d+)?)(.+?(version\/(\d+(\.\d+)?)))?/i.test(navigator.userAgent)?+(RegExp.$6||RegExp.$2):void 0;
baidu.dom.insertHTML=function(a,b,d){a=baidu.dom.g(a);var c;a.insertAdjacentHTML&&!baidu.browser.opera?a.insertAdjacentHTML(b,d):(c=a.ownerDocument.createRange(),b=b.toUpperCase(),"AFTERBEGIN"==b||"BEFOREEND"==b?(c.selectNodeContents(a),c.collapse("AFTERBEGIN"==b)):(b="BEFOREBEGIN"==b,c[b?"setStartBefore":"setEndAfter"](a),c.collapse(b)),c.insertNode(c.createContextualFragment(d)));return a};baidu.insertHTML=baidu.dom.insertHTML;baidu.swf=baidu.swf||{};
baidu.swf.version=function(){var a=navigator;if(a.plugins&&a.mimeTypes.length){var b=a.plugins["Shockwave Flash"];if(b&&b.description)return b.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0"}else if(window.ActiveXObject&&!window.opera)for(a=12;2<=a;a--)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+a))return b.GetVariable("$version").replace(/WIN/g,"").replace(/,/g,".")}catch(d){}}();baidu.string=baidu.string||{};
baidu.string.encodeHTML=function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};baidu.encodeHTML=baidu.string.encodeHTML;
baidu.swf.createHTML=function(a){a=a||{};var b=baidu.swf.version,d=a.ver||"6.0.0",c,g,e,f;e={};var h=baidu.string.encodeHTML;for(f in a)e[f]=a[f];a=e;if(b)for(b=b.split("."),d=d.split("."),e=0;3>e&&!(c=parseInt(b[e],10),g=parseInt(d[e],10),g<c);e++){if(g>c)return""}else return"";e=a.vars;d="classid codebase id width height align".split(" ");a.align=a.align||"middle";a.classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000";a.codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0";
a.movie=a.url||"";delete a.vars;delete a.url;if("string"==typeof e)a.flashvars=e;else{c=[];for(f in e)b=e[f],c.push(f+"="+encodeURIComponent(b));a.flashvars=c.join("&")}c=["<object "];e=0;for(g=d.length;e<g;e++)b=d[e],c.push(" ",b,'="',h(a[b]),'"');c.push(">");e={wmode:1,scale:1,quality:1,play:1,loop:1,menu:1,salign:1,bgcolor:1,base:1,allowscriptaccess:1,allownetworking:1,allowfullscreen:1,seamlesstabbing:1,devicefont:1,swliveconnect:1,flashvars:1,movie:1};for(f in a)b=a[f],f=f.toLowerCase(),e[f]&&
(b||!1===b||0===b)&&c.push('<param name="'+f+'" value="'+h(b)+'" />');a.src=a.movie;a.name=a.id;delete a.id;delete a.movie;delete a.classid;delete a.codebase;a.type="application/x-shockwave-flash";a.pluginspage="http://www.macromedia.com/go/getflashplayer";c.push("<embed");var k;for(f in a)if((b=a[f])||!1===b||0===b)/^salign$/i.test(f)?k=b:c.push(" ",f,'="',h(b),'"');k&&c.push(' salign="',h(k),'"');c.push("></embed></object>");return c.join("")};
baidu.swf.create=function(a,b){a=a||{};var d=baidu.swf.createHTML(a)||a.errorMessage||"";b&&"string"==typeof b&&(b=document.getElementById(b));baidu.dom.insertHTML(b||document.body,"beforeEnd",d)};baidu.browser.ie=baidu.ie=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:void 0;baidu.array.remove=function(a,b){for(var d=a.length;d--;)d in a&&a[d]===b&&a.splice(d,1);return a};baidu.lang.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)};
baidu.lang.toArray=function(a){if(null===a||void 0===a)return[];if(baidu.lang.isArray(a))return a;if("number"!==typeof a.length||"string"===typeof a||baidu.lang.isFunction(a))return[a];if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)};baidu.swf.getMovie=function(a){var b=document[a],d;return 9==baidu.browser.ie?b&&b.length?1==(d=baidu.array.remove(baidu.lang.toArray(b),function(a){return"embed"!=a.tagName.toLowerCase()})).length?d[0]:d:b:b||window[a]};
baidu.flash._Base=function(){function a(a,b){var d=null;a=a.reverse();baidu.each(a,function(a){d=b.call(a.fnName,a.params);a.callBack(d)})}function b(a){var b="";if(baidu.lang.isFunction(a))return b="bd__flash__"+Math.floor(2147483648*Math.random()).toString(36),window[b]=function(){a.apply(window,arguments)},b;if(baidu.lang.isString)return a}function d(a){a.id||(a.id="bd__flash__"+Math.floor(2147483648*Math.random()).toString(36));var b=a.container||"";delete a.container;baidu.swf.create(a,b);return baidu.swf.getMovie(a.id)}
return function(c,g){function e(){var b;b="undefined"!==typeof l&&"undefined"!==typeof l.flashInit&&l.flashInit()?!0:!1;b&&(clearInterval(p),p=null,a(n,l),n=[],m=!0)}var f=this,h="undefined"!==typeof c.autoRender?c.autoRender:!0,k=c.createOptions||{},l=null,m=!1,n=[],p=null;g=g||[];f.render=function(){l=d(k);0<g.length&&baidu.each(g,function(a,d){g[d]=b(c[a]||new Function)});f.call("setJSFuncName",[g])};f.isReady=function(){return m};f.call=function(a,b,d){if(!a)return null;d=d||new Function;var c=
null;m?(c=l.call(a,b),d(c)):(n.push({fnName:a,params:b,callBack:d}),!p&&(p=setInterval(e,200)))};f.createFunName=function(a){return b(a)};h&&f.render()}}();
baidu.flash.imageUploader=baidu.flash.imageUploader||function(a){a=a||{};var b=new baidu.flash._Base(a,"selectFileCallback exceedFileCallback deleteFileCallback startUploadCallback uploadCompleteCallback uploadErrorCallback allCompleteCallback changeFlashHeight".split(" "));this.upload=function(){b.call("upload")};this.pause=function(){b.call("pause")};this.addCustomizedParams=function(a,c){b.call("addCustomizedParams",[a,c])}};baidu.object=baidu.object||{};
baidu.extend=baidu.object.extend=function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a};
baidu.flash.fileUploader=baidu.flash.fileUploader||function(a){a=a||{};a.createOptions=baidu.extend({wmod:"transparent"},a.createOptions||{});var b=new baidu.flash._Base(a,"selectFile exceedMaxSize deleteFile uploadStart uploadComplete uploadError uploadProgress".split(" "));b.call("setMaxNum",a.maxNum?[a.maxNum]:[1]);this.setHandCursor=function(a){b.call("setHandCursor",[a||!1])};this.setMSFunName=function(a){b.call("setMSFunName",[b.createFunName(a)])};this.upload=function(a,c,g,e){if("string"!==
typeof a||"string"!==typeof c)return null;"undefined"===typeof e&&(e=-1);b.call("upload",[a,c,g,e])};this.cancel=function(a){"undefined"===typeof a&&(a=-1);b.call("cancel",[a])};this.deleteFile=function(a,c){var g=function(a){c&&c(a)};"undefined"===typeof a?b.call("deleteFilesAll",[],g):("Number"===typeof a&&(a=[a]),a.sort(function(a,b){return b-a}),baidu.each(a,function(a){b.call("deleteFileBy",a,g)}))};this.addFileType=function(a){a=a||[[]];a=a instanceof Array?[a]:[[a]];b.call("addFileTypes",a)};
this.setFileType=function(a){a=a||[[]];a=a instanceof Array?[a]:[[a]];b.call("setFileTypes",a)};this.setMaxNum=function(a){b.call("setMaxNum",[a])};this.setMaxSize=function(a){b.call("setMaxSize",[a])};this.getFileAll=function(a){b.call("getFileAll",[],a)};this.getFileByIndex=function(a,c){b.call("getFileByIndex",[],c)};this.getStatusByIndex=function(a,c){b.call("getStatusByIndex",[],c)}};baidu.sio=baidu.sio||{};
baidu.sio._createScriptTag=function(a,b,d){a.setAttribute("type","text/javascript");d&&a.setAttribute("charset",d);a.setAttribute("src",b);document.getElementsByTagName("head")[0].appendChild(a)};baidu.sio._removeScriptTag=function(a){if(a.clearAttributes)a.clearAttributes();else for(var b in a)a.hasOwnProperty(b)&&delete a[b];a&&a.parentNode&&a.parentNode.removeChild(a)};
baidu.sio.callByBrowser=function(a,b,d){var c=document.createElement("SCRIPT"),g=0,e=d||{};d=e.charset;var f=b||function(){};b=e.timeOut||0;var h;c.onload=c.onreadystatechange=function(){if(!g){var a=c.readyState;if("undefined"==typeof a||"loaded"==a||"complete"==a){g=1;try{f(),clearTimeout(h)}finally{c.onload=c.onreadystatechange=null,baidu.sio._removeScriptTag(c)}}}};b&&(h=setTimeout(function(){c.onload=c.onreadystatechange=null;baidu.sio._removeScriptTag(c);e.onfailure&&e.onfailure()},b));baidu.sio._createScriptTag(c,
a,d)};
baidu.sio.callByServer=function(a,b,d){function c(a){return function(){try{a?f.onfailure&&f.onfailure():(b.apply(window,arguments),clearTimeout(l)),window[e]=null,delete window[e]}catch(c){}finally{baidu.sio._removeScriptTag(g)}}}var g=document.createElement("SCRIPT"),e,f=d||{};d=f.charset;var h=f.queryField||"callback",k=f.timeOut||0,l,m=new RegExp("(\\?|&)"+h+"=([^&]*)"),n;if(baidu.lang.isFunction(b))e="bd__cbs__"+Math.floor(2147483648*Math.random()).toString(36),window[e]=c(0);else if(baidu.lang.isString(b))e=b;
else if(n=m.exec(a))e=n[2];k&&(l=setTimeout(c(1),k));a=a.replace(m,"$1"+h+"="+e);0>a.search(m)&&(a+=(0>a.indexOf("?")?"?":"&")+h+"="+e);baidu.sio._createScriptTag(g,a,d)};baidu.sio.log=function(a){var b=new Image,d="tangram_sio_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=null;b=window[d]=null};b.src=a};baidu.json=baidu.json||{};baidu.json.parse=function(a){return(new Function("return ("+a+")"))()};
baidu.json.decode=baidu.json.parse;
baidu.json.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(c){switch(typeof c){case "undefined":return"undefined";case "number":return isFinite(c)?String(c):"null";case "string":return a(c);
case "boolean":return String(c);default:if(null===c)return"null";if(c instanceof Array){var d=["["],e=c.length,f,h,k;for(h=0;h<e;h++)switch(k=c[h],typeof k){case "undefined":case "function":case "unknown":break;default:f&&d.push(","),d.push(baidu.json.stringify(k)),f=1}d.push("]");return d.join("")}if(c instanceof Date)return'"'+c.getFullYear()+"-"+b(c.getMonth()+1)+"-"+b(c.getDate())+"T"+b(c.getHours())+":"+b(c.getMinutes())+":"+b(c.getSeconds())+'"';f=["{"];h=baidu.json.stringify;for(e in c)if(Object.prototype.hasOwnProperty.call(c,
e))switch(k=c[e],typeof k){case "undefined":case "unknown":case "function":break;default:d&&f.push(","),d=1,f.push(h(e)+":"+h(k))}f.push("}");return f.join("")}}}();baidu.json.encode=baidu.json.stringify;