(function(){function m(){for(var a=$G("tabHeads").children,b=0;b<a.length;b++)domUtils.on(a[b],"click",function(b){b=b.target||b.srcElement;for(var e=0;e<a.length;e++)if(a[e]==b){a[e].className="focus";var d=a[e].getAttribute("data-content-id");$G(d).style.display="block";"imgManager"==d&&(k=k||new l("imageList"))}else a[e].className="",$G(a[e].getAttribute("data-content-id")).style.display="none"})}function n(){var a=editor.queryCommandValue("background");if(a){var b=a["background-color"],c=a["background-repeat"]||
"repeat",e=a["background-image"]||"",d=(a["background-position"]||"center center").split(" "),a=parseInt(d[0])||0,d=parseInt(d[1])||0;"no-repeat"==c&&(a||d)&&(c="self");e=(e=e.match(/url[\s]*\(([^\)]*)\)/))?e[1]:"";g("colored",b,e,c,a,d)}else g();var f=function(){g();h()};domUtils.on($G("nocolorRadio"),"click",h);domUtils.on($G("coloredRadio"),"click",f);domUtils.on($G("url"),"keyup",function(){$G("url").value&&"none"==$G("alignment").style.display&&utils.each($G("repeatType").children,function(a){a.selected=
"repeat"==a.getAttribute("value")?"selected":!1});f()});domUtils.on($G("repeatType"),"change",f);domUtils.on($G("x"),"keyup",h);domUtils.on($G("y"),"keyup",h);p()}function p(){var a=editor,b=$G("colorPicker"),c=new UE.ui.Popup({content:new UE.ui.ColorPicker({noColorText:a.getLang("clearColor"),editor:a,onpickcolor:function(a,b){g("colored",b);h();UE.ui.Popup.postHide()},onpicknocolor:function(a,b){g("colored","transparent");h();UE.ui.Popup.postHide()}}),editor:a,onhide:function(){}});domUtils.on(b,
"click",function(){c.showAnchor(this)});domUtils.on(document,"mousedown",function(a){UE.ui.Popup.postHide(a.target||a.srcElement)});domUtils.on(window,"scroll",function(){UE.ui.Popup.postHide()})}function g(a,b,c,e,d,f){var h=$G("nocolorRadio"),g=$G("coloredRadio");a&&(h.checked="colored"==a?!1:"checked",g.checked="colored"==a?"checked":!1);b&&domUtils.setStyle($G("colorPicker"),"background-color",b);c&&/^\//.test(c)&&(a=document.createElement("a"),a.href=c,browser.ie&&(a.href=a.href),c=browser.ie?
a.href:a.protocol+"//"+a.host+a.pathname+a.search+a.hash);if(c||""===c)$G("url").value=c;e&&utils.each($G("repeatType").children,function(a){a.selected=e==a.getAttribute("value")?"selected":!1});if(d||f)$G("x").value=parseInt(d)||0,$G("y").value=parseInt(f)||0;$G("alignment").style.display=g.checked&&$G("url").value?"":"none";$G("custom").style.display=g.checked&&$G("url").value&&"self"==$G("repeatType").value?"":"none"}function h(){if($G("coloredRadio").checked){var a=domUtils.getStyle($G("colorPicker"),
"background-color"),b=$G("url").value,c=$G("repeatType").value,e={"background-repeat":"no-repeat","background-position":"center center"};a&&(e["background-color"]=a);b&&(e["background-image"]="url("+b+")");if("self"==c)e["background-position"]=$G("x").value+"px "+$G("y").value+"px";else if("repeat-x"==c||"repeat-y"==c||"repeat"==c)e["background-repeat"]=c;editor.execCommand("background",e)}else editor.execCommand("background",null)}function l(a){this.container=utils.isString(a)?document.getElementById(a):
a;this.init()}var k,q=editor.queryCommandValue("background");window.onload=function(){m();n()};l.prototype={init:function(){this.reset();this.initEvents()},initContainer:function(){this.container.innerHTML="";this.list=document.createElement("ul");this.clearFloat=document.createElement("li");domUtils.addClass(this.list,"list");domUtils.addClass(this.clearFloat,"clearFloat");this.list.id="imageListUl";this.list.appendChild(this.clearFloat);this.container.appendChild(this.list)},initEvents:function(){var a=
this;domUtils.on($G("imageList"),"scroll",function(b){10>this.scrollHeight-(this.offsetHeight+this.scrollTop)&&a.getImageData()});domUtils.on(this.container,"click",function(a){a=(a.target||a.srcElement).parentNode;var c=$G("imageListUl").childNodes;if("li"==a.tagName.toLowerCase()){g("nocolor",null,"");for(var e=0,d;d=c[e++];)d!=a||domUtils.hasClass(d,"selected")?domUtils.removeClasses(d,"selected"):(domUtils.addClass(d,"selected"),g("colored",null,a.firstChild.getAttribute("_src"),"repeat"));h()}})},
initData:function(){this.state=0;this.listSize=editor.getOpt("imageManagerListSize");this.listIndex=0;this.listEnd=!1;this.getImageData()},reset:function(){this.initContainer();this.initData()},getImageData:function(){var a=this;if(!a.listEnd&&!this.isLoadingData){this.isLoadingData=!0;var b=editor.getActionUrl(editor.getOpt("imageManagerActionName")),c=utils.isCrossDomainUrl(b);ajax.request(b,{timeout:1E5,dataType:c?"jsonp":"",data:utils.extend({start:this.listIndex,size:this.listSize},editor.queryCommandValue("serverparam")),
method:"get",onsuccess:function(b){try{var d=c?b:eval("("+b.responseText+")");"SUCCESS"==d.state&&(a.pushData(d.list),a.listIndex=parseInt(d.start)+parseInt(d.list.length),a.listIndex>=d.total&&(a.listEnd=!0),a.isLoadingData=!1)}catch(f){-1!=b.responseText.indexOf("ue_separate_ue")&&(b=b.responseText.split(b.responseText),a.pushData(b),a.listIndex=parseInt(b.length),a.listEnd=!0,a.isLoadingData=!1)}},onerror:function(){a.isLoadingData=!1}})}},pushData:function(a){var b,c,e,d,f=this,g=editor.getOpt("imageManagerUrlPrefix");
for(b=0;b<a.length;b++)a[b]&&a[b].url&&(c=document.createElement("li"),e=document.createElement("img"),d=document.createElement("span"),domUtils.on(e,"load",function(a){return function(){f.scale(a,a.parentNode.offsetWidth,a.parentNode.offsetHeight)}}(e)),e.width=113,e.setAttribute("src",g+a[b].url+(-1==a[b].url.indexOf("?")?"?noCache=":"&noCache=")+(+new Date).toString(36)),e.setAttribute("_src",g+a[b].url),domUtils.addClass(d,"icon"),c.appendChild(e),c.appendChild(d),this.list.insertBefore(c,this.clearFloat))},
scale:function(a,b,c,e){var d=a.width,f=a.height;"justify"==e?d>=f?(a.width=b,a.height=c*f/d,a.style.marginLeft="-"+parseInt((a.width-b)/2)+"px"):(a.width=b*d/f,a.height=c,a.style.marginTop="-"+parseInt((a.height-c)/2)+"px"):d>=f?(a.width=b*d/f,a.height=c,a.style.marginLeft="-"+parseInt((a.width-b)/2)+"px"):(a.width=b,a.height=c*f/d,a.style.marginTop="-"+parseInt((a.height-c)/2)+"px")},getInsertList:function(){var a,b=this.list.children,c=[],e=getAlign();for(a=0;a<b.length;a++)if(domUtils.hasClass(b[a],
"selected")){var d=b[a].firstChild.getAttribute("_src");c.push({src:d,_src:d,floatStyle:e})}return c}};dialog.onok=function(){h();editor.fireEvent("saveScene")};dialog.oncancel=function(){editor.execCommand("background",q)}})();