var scrawl=function(f){f&&this.initOptions(f)};
(function(){var f=$G("J_brushBoard"),d=f.getContext("2d"),e=[],c=0;scrawl.prototype={isScrawl:!1,brushWidth:-1,brushColor:"",initOptions:function(b){this.originalState(b);this._buildToolbarColor(b.colorList);this._addBoardListener(b.saveNum);this._addOPerateListener(b.saveNum);this._addColorBarListener();this._addBrushBarListener();this._addEraserBarListener();this._addAddImgListener();this._addRemoveImgListenter();this._addScalePicListenter();this._addClearSelectionListenter();this._originalColorSelect(b.drawBrushColor);
this._originalBrushSelect(b.drawBrushSize);this._clearSelection()},originalState:function(b){this.brushWidth=b.drawBrushSize;this.brushColor=b.drawBrushColor;d.lineWidth=this.brushWidth;d.strokeStyle=this.brushColor;d.fillStyle="transparent";d.lineCap="round";d.fill()},_buildToolbarColor:function(b){var a=null,g=[];g.push("<table id='J_colorList'>");for(var c=0;a=b[c++];)0==(c-1)%5&&(1!=c&&g.push("</tr>"),g.push("<tr>")),a="#"+a,g.push("<td><a title='"+a+"' href='javascript:void(0)' style='background-color:"+
a+"'></a></td>");g.push("</tr></table>");$G("J_colorBar").innerHTML=g.join("")},_addBoardListener:function(b){var a=this,g=0,h=-1,k=-1,m=!1,n=!1,r=!1,p=0,q,l="",g=parseInt(domUtils.getComputedStyle($G("J_wrap"),"margin-left"));e.push(d.getImageData(0,0,d.canvas.width,d.canvas.height));c+=1;domUtils.on(f,["mousedown","mousemove","mouseup","mouseout"],function(c){q=browser.webkit?c.which:p;switch(c.type){case "mousedown":l=p=1;m=!0;n=r=!1;a.isScrawl=!0;h=c.clientX-g;k=c.clientY-g;d.beginPath();break;
case "mousemove":if(!l&&0==q)break;!l&&q&&(h=c.clientX-g,k=c.clientY-g,d.beginPath(),l=1);if(r||!m)break;var e=c.clientX-g;c=c.clientY-g;d.moveTo(h,k);d.lineTo(e,c);d.stroke();h=e;k=c;n=!0;break;case "mouseup":p=0;if(!m)break;n||(d.arc(h,k,d.lineWidth,0,2*Math.PI,!1),d.fillStyle=d.strokeStyle,d.fill());d.closePath();a._saveOPerate(b);n=m=!1;r=!0;k=h=-1;break;case "mouseout":l="";p=0;if(1==q)break;d.closePath()}})},_addOPerateListener:function(b){var a=this;domUtils.on($G("J_previousStep"),"click",
function(){1<c&&(--c,d.clearRect(0,0,d.canvas.width,d.canvas.height),d.putImageData(e[c-1],0,0),a.btn2Highlight("J_nextStep"),1==c&&a.btn2disable("J_previousStep"))});domUtils.on($G("J_nextStep"),"click",function(){0<c&&c<e.length&&(d.clearRect(0,0,d.canvas.width,d.canvas.height),d.putImageData(e[c],0,0),c+=1,a.btn2Highlight("J_previousStep"),c==e.length&&a.btn2disable("J_nextStep"))});domUtils.on($G("J_clearBoard"),"click",function(){d.clearRect(0,0,d.canvas.width,d.canvas.height);e=[];a._saveOPerate(b);
c=1;a.isScrawl=!1;a.btn2disable("J_previousStep");a.btn2disable("J_nextStep");a.btn2disable("J_clearBoard")})},_addColorBarListener:function(){var b=this;domUtils.on($G("J_colorBar"),"click",function(a){a=b.getTarget(a);var c=a.title;c&&(b._addColorSelect(a),b.brushColor=c,d.globalCompositeOperation="source-over",d.lineWidth=b.brushWidth,d.strokeStyle=c)})},_addBrushBarListener:function(){var b=this;domUtils.on($G("J_brushBar"),"click",function(a){a=b.getTarget(a);var c=browser.ie?a.innerText:a.text;
c&&(b._addBESelect(a),d.globalCompositeOperation="source-over",d.lineWidth=parseInt(c),d.strokeStyle=b.brushColor,b.brushWidth=d.lineWidth)})},_addEraserBarListener:function(){var b=this;domUtils.on($G("J_eraserBar"),"click",function(a){a=b.getTarget(a);var c=browser.ie?a.innerText:a.text;c&&(b._addBESelect(a),d.lineWidth=parseInt(c),d.globalCompositeOperation="destination-out",d.strokeStyle="#FFF")})},_addAddImgListener:function(){var b=$G("J_imgTxt");window.FileReader||($G("J_addImg").style.display=
"none",$G("J_removeImg").style.display="none",$G("J_sacleBoard").style.display="none");domUtils.on(b,"change",function(a){var c=b.parentNode;addMaskLayer(lang.backgroundUploading);a=a.target||a.srcElement;var d=new FileReader;d.onload=function(a){ue_callback((a.target||a.srcElement).result,"SUCCESS")};d.readAsDataURL(a.files[0]);c.reset()})},_addRemoveImgListenter:function(){var b=this;domUtils.on($G("J_removeImg"),"click",function(){$G("J_picBoard").innerHTML="";b.btn2disable("J_removeImg");b.btn2disable("J_sacleBoard")})},
_addScalePicListenter:function(){domUtils.on($G("J_sacleBoard"),"click",function(){var b=$G("J_picBoard"),a=$G("J_scaleCon"),c=b.children[0];c&&(a?"visible"==a.style.visibility?(a.style.visibility="hidden",b.style.position="",b.style.zIndex=""):(a.style.visibility="visible",b.style.cssText+="position:relative;z-index:999"):(b.style.cssText="position:relative;z-index:999;"+b.style.cssText,c.style.cssText="position: absolute;top:"+(f.height-c.height)/2+"px;left:"+(f.width-c.width)/2+"px;",a=new ScaleBoy,
b.appendChild(a.init()),a.startScale(c)))})},_addClearSelectionListenter:function(){var b=document;domUtils.on(b,"mousemove",function(a){browser.ie&&11>browser.version?b.selection.clear():window.getSelection().removeAllRanges()})},_clearSelection:function(){for(var b=["J_operateBar","J_colorBar","J_brushBar","J_eraserBar","J_picBoard"],a=0,c;c=b[a++];)domUtils.unSelectable($G(c))},_saveOPerate:function(b){e.length<=b?c<e.length&&(this.btn2disable("J_nextStep"),e.splice(c)):e.shift();e.push(d.getImageData(0,
0,d.canvas.width,d.canvas.height));c=e.length;this.btn2Highlight("J_previousStep");this.btn2Highlight("J_clearBoard")},_originalColorSelect:function(b){for(var a=$G("J_colorList").getElementsByTagName("td"),c=0,d;d=a[c++];)d.children[0].title.toLowerCase()==b&&(d.children[0].style.opacity=1)},_originalBrushSelect:function(b){for(var a=$G("J_brushBar").children,c=0,d;d=a[c++];)"a"==d.tagName.toLowerCase()&&(browser.ie?d.innerText:d.text).toLowerCase()==b&&(d.style.opacity=1)},_addColorSelect:function(b){for(var a=
$G("J_colorList").getElementsByTagName("td"),c=$G("J_eraserBar").children,d=$G("J_brushBar").children,e=0,f;f=a[e++];)f.children[0].style.opacity=.3;for(a=0;e=d[a++];)"a"==e.tagName.toLowerCase()&&(e.style.opacity=.3,(browser.ie?e.innerText:e.text).toLowerCase()==this.brushWidth&&(e.style.opacity=1));for(d=0;a=c[d++];)"a"==a.tagName.toLowerCase()&&(a.style.opacity=.3);b.style.opacity=1;b.blur()},_addBESelect:function(b){for(var a=$G("J_brushBar").children,c=$G("J_eraserBar").children,d=0,e;e=a[d++];)"a"==
e.tagName.toLowerCase()&&(e.style.opacity=.3);for(a=0;d=c[a++];)"a"==d.tagName.toLowerCase()&&(d.style.opacity=.3);b.style.opacity=1;b.blur()},getCanvasData:function(){var b=$G("J_picBoard"),a=b.children[0];if(a){var c;"absolute"==a.style.position?(c=parseInt(a.style.left),b=parseInt(a.style.top)):(c=(b.offsetWidth-a.width)/2,b=(b.offsetHeight-a.height)/2);d.globalCompositeOperation="destination-over";d.drawImage(a,c,b,a.width,a.height)}else d.globalCompositeOperation="destination-atop",d.fillStyle=
"#fff",d.fillRect(0,0,f.width,f.height);try{return f.toDataURL("image/png").substring(22)}catch(e){return""}},btn2Highlight:function(b){b=$G(b);-1==b.className.indexOf("H")&&(b.className+="H")},btn2disable:function(b){b=$G(b);-1!=b.className.indexOf("H")&&(b.className=b.className.replace("H",""))},getTarget:function(b){return b.target||b.srcElement}}})();var ScaleBoy=function(){this.scalingElement=this.dom=null};
(function(){function f(){var c=document,b=c.getElementsByTagName("head")[0],a=c.createElement("style");a.type="text/css";try{a.appendChild(c.createTextNode(".scale{visibility:hidden;cursor:move;position:absolute;left:0;top:0;width:100px;height:50px;background-color:#fff;font-size:0;line-height:0;opacity:.4;filter:Alpha(opacity=40);}.scale span{position:absolute;left:0;top:0;width:6px;height:6px;background-color:#006DAE;}.scale .hand0, .scale .hand7{cursor:nw-resize;}.scale .hand1, .scale .hand6{left:50%;margin-left:-3px;cursor:n-resize;}.scale .hand2, .scale .hand4, .scale .hand7{left:100%;margin-left:-6px;}.scale .hand3, .scale .hand4{top:50%;margin-top:-3px;cursor:w-resize;}.scale .hand5, .scale .hand6, .scale .hand7{margin-top:-6px;top:100%;}.scale .hand2, .scale .hand5{cursor:ne-resize;}"))}catch(d){a.styleSheet.cssText=
".scale{visibility:hidden;cursor:move;position:absolute;left:0;top:0;width:100px;height:50px;background-color:#fff;font-size:0;line-height:0;opacity:.4;filter:Alpha(opacity=40);}.scale span{position:absolute;left:0;top:0;width:6px;height:6px;background-color:#006DAE;}.scale .hand0, .scale .hand7{cursor:nw-resize;}.scale .hand1, .scale .hand6{left:50%;margin-left:-3px;cursor:n-resize;}.scale .hand2, .scale .hand4, .scale .hand7{left:100%;margin-left:-6px;}.scale .hand3, .scale .hand4{top:50%;margin-top:-3px;cursor:w-resize;}.scale .hand5, .scale .hand6, .scale .hand7{margin-top:-6px;top:100%;}.scale .hand2, .scale .hand5{cursor:ne-resize;}"}b.appendChild(a)}
function d(){var c=[],b=document.createElement("div");b.id="J_scaleCon";b.className="scale";for(var a=0;8>a;a++)c.push("<span class='hand"+a+"'></span>");b.innerHTML=c.join("");return b}var e=[[1,1,-1,-1],[0,1,0,-1],[0,1,1,-1],[1,0,-1,0],[0,0,1,0],[1,0,-1,1],[0,0,0,1],[0,0,1,1]];ScaleBoy.prototype={init:function(){f();var c=this,b=c.dom=d();c.scaleMousemove.fp=c;domUtils.on(b,"mousedown",function(a){var b=a.target||a.srcElement;c.start={x:a.clientX,y:a.clientY};-1!=b.className.indexOf("hand")&&(c.dir=
b.className.replace("hand",""));domUtils.on(document.body,"mousemove",c.scaleMousemove);a.stopPropagation?a.stopPropagation():a.cancelBubble=!0});domUtils.on(document.body,"mouseup",function(a){c.start&&(domUtils.un(document.body,"mousemove",c.scaleMousemove),c.moved&&c.updateScaledElement({position:{x:b.style.left,y:b.style.top},size:{w:b.style.width,h:b.style.height}}),delete c.start,delete c.moved,delete c.dir)});return b},startScale:function(c){this.dom.style.cssText="visibility:visible;top:"+
c.style.top+";left:"+c.style.left+";width:"+c.offsetWidth+"px;height:"+c.offsetHeight+"px;";this.scalingElement=c},updateScaledElement:function(c){var b=this.scalingElement,a=c.position;c=c.size;a&&("undefined"!=typeof a.x&&(b.style.left=a.x),"undefined"!=typeof a.y&&(b.style.top=a.y));c&&(c.w&&(b.style.width=c.w),c.h&&(b.style.height=c.h))},updateStyleByDir:function(c,b){var a=this.dom,d;e.def=[1,1,0,0];0!=e[c][0]&&(d=parseInt(a.style.left)+b.x,a.style.left=this._validScaledProp("left",d)+"px");
0!=e[c][1]&&(d=parseInt(a.style.top)+b.y,a.style.top=this._validScaledProp("top",d)+"px");0!=e[c][2]&&(d=a.clientWidth+e[c][2]*b.x,a.style.width=this._validScaledProp("width",d)+"px");0!=e[c][3]&&(d=a.clientHeight+e[c][3]*b.y,a.style.height=this._validScaledProp("height",d)+"px");"def"===c&&this.updateScaledElement({position:{x:a.style.left,y:a.style.top}})},scaleMousemove:function(c){var b=arguments.callee.fp,a=b.start;b.updateStyleByDir(b.dir||"def",{x:c.clientX-a.x,y:c.clientY-a.y});arguments.callee.fp.start=
{x:c.clientX,y:c.clientY};arguments.callee.fp.moved=1},_validScaledProp:function(c,b){var a=this.dom,d=$G("J_picBoard");b=isNaN(b)?0:b;switch(c){case "left":return 0>b?0:b+a.clientWidth>d.clientWidth?d.clientWidth-a.clientWidth:b;case "top":return 0>b?0:b+a.clientHeight>d.clientHeight?d.clientHeight-a.clientHeight:b;case "width":return 0>=b?1:b+a.offsetLeft>d.clientWidth?d.clientWidth-a.offsetLeft:b;case "height":return 0>=b?1:b+a.offsetTop>d.clientHeight?d.clientHeight-a.offsetTop:b}}}})();
function ue_callback(f,d){var e=document,c=$G("J_picBoard"),b=e.createElement("img");removeMaskLayer();"SUCCESS"==d?(c.innerHTML="",b.onload=function(){var a=0,a=0,d=this.width||void 0,e=this.height||void 0;if(300<d||300<e)if(d>=e){if(a=d-300)a=(a/d).toFixed(2),this.height=e-e*a,this.width=300}else if(a=e-300)a=(a/e).toFixed(2),this.width=d-d*a,this.height=300;c.appendChild(b);d=new scrawl;d.btn2Highlight("J_removeImg");d.btn2Highlight("J_sacleBoard")},b.src=f):alert(d)}
function removeMaskLayer(){var f=$G("J_maskLayer");f.className="maskLayerNull";f.innerHTML="";dialog.buttons[0].setDisabled(!1)}function addMaskLayer(f){var d=$G("J_maskLayer");dialog.buttons[0].setDisabled(!0);d.className="maskLayer";d.innerHTML=f}
function exec(f){if(f.isScrawl){addMaskLayer(lang.scrawlUpLoading);var d=f.getCanvasData();if(d){var e={timeout:1E5,onsuccess:function(b){if(!f.isCancelScrawl)if(b=eval("("+b.responseText+")"),"SUCCESS"==b.state){var a={},c=editor.options.scrawlUrlPrefix+b.url;a.src=c;a._src=c;a.alt=b.original||"";a.title=b.title||"";editor.execCommand("insertImage",a);dialog.close()}else alert(b.state)},onerror:function(){alert(lang.imageError);dialog.close()}};e[editor.getOpt("scrawlFieldName")]=d;var d=editor.getActionUrl(editor.getOpt("scrawlActionName")),
c=utils.serializeParam(editor.queryCommandValue("serverparam"))||"",d=utils.formatUrl(d+(-1==d.indexOf("?")?"?":"&")+c);ajax.request(d,e)}}else addMaskLayer(lang.noScarwl+"&nbsp;&nbsp;&nbsp;<input type='button' value='"+lang.continueBtn+"'  onclick='removeMaskLayer()'/>")};